name: Build
on:
  push:

jobs:
  linux-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hairyhenderson/gomplate-ci-build:1.18
    steps:
      - run: |
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
      - uses: actions/checkout@v2.4.0
        with:
          path: ./src/github.com/${{ github.repository }}
      - run: make build
        env:
          GOPATH: ${{ runner.workspace }}
          ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH: go1.18rc1
      - name: Save binary
        uses: actions/upload-artifact@v3
        with:
          name: gomplate
          path: bin/gomplate
      - name: make test
        run: |
          [ -n "$CC_TEST_REPORTER_ID" ] && cc-test-reporter before-build
          make test
          EXIT_CODE=$?

          if [ -n "$CC_TEST_REPORTER_ID" ]; then
            # workaround from https://github.com/codeclimate/test-reporter/issues/378
            export PREFIX=$(basename $(go list -m))
            cc-test-reporter after-build -t gocov -p $PREFIX --exit-code $EXIT_CODE
          fi
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          GOPATH: ${{ runner.workspace }}
          ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH: go1.18rc1
      - run: make integration
        env:
          GOPATH: ${{ runner.workspace }}
          ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH: go1.18rc1
  windows-build:
    runs-on: windows-latest
    env:
      TMP: D:\tmp
      ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH: go1.18rc1
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18.0-rc1'
      - run: |
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
      - uses: actions/checkout@v2.4.0
        with:
          path: ./src/github.com/${{ github.repository }}
      - run: make build
        env:
          GOPATH: ${{ runner.workspace }}
      - name: Save binary
        uses: actions/upload-artifact@v3
        with:
          name: gomplate.exe
          path: bin/gomplate.exe
      - run: make test
        env:
          GOPATH: ${{ runner.workspace }}
      - run: make integration
        env:
          GOPATH: ${{ runner.workspace }}
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hairyhenderson/gomplate-ci-build:latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          path: ./src/github.com/${{ github.repository }}
      - run: make ci-lint
        env:
          ASSUME_NO_MOVING_GC_UNSAFE_RISK_IT_WITH: go1.18rc1
